Tankad=int(input())
Price=int(input())
Paid=(Tankad * Price)
a=("---------------------------------------------------")
b=("|                                                 |")
d=("|                     KVITTO                      |")
m=("|                                                 |")
f=("|Tanked Volume     ")
c=("liters            |")
u=("|price per liter   ")
h=("kr                |")
t=("|Paid kroner       ")
n=("                  |")
w=("|Thank you for visiting and welcome back          |")
k=("---------------------------------------------------")
print (a,"\n",b,"\n",d,"\n",m,"\n",f,Tankad,c,"\n",u,Price,h,"\n",t,Paid,n,"\n",w,"\n",k)